import { IServiceCardContentProps } from './types';

export const SERVICE_CARD_CONTENT: IServiceCardContentProps[] = [
  {
    id: 'search-engine-optimization',
    title: 'Search engine',
    subtitle: 'optimization',
    background: 'light',
    headingVariant: 'green',
    href: '#services',
    backgroundArrowLink: 'dark',
    image: {
      src: '/illustrations/services/search-engine.webp',
      alt: 'Ilustração representando otimização para mecanismos de busca',
      width: 210,
      height: 170,
    },
  },
  {
    id: 'pay-per-click-advertising',
    title: 'Pay-per-click',
    subtitle: 'advertising',
    background: 'green',
    headingVariant: 'white',
    href: '#services',
    backgroundArrowLink: 'dark',
    image: {
      src: '/illustrations/services/pay-per-click.webp',
      alt: 'Ilustração representando publicidade paga por clique',
      width: 210,
      height: 147,
    },
  },
  {
    id: 'social-media-marketing',
    title: 'Social Media',
    subtitle: 'Marketing',
    background: 'dark',
    headingVariant: 'white',
    href: '#services',
    backgroundArrowLink: 'alternative-light',
    image: {
      src: '/illustrations/services/social-media.webp',
      alt: 'Ilustração representando marketing em redes sociais',
      width: 210,
      height: 210,
    },
  },
  {
    id: 'email-marketing',
    title: 'Email',
    subtitle: 'Marketing',
    background: 'light',
    headingVariant: 'green',
    href: '#services',
    backgroundArrowLink: 'dark',
    image: {
      src: '/illustrations/services/email-marketing.webp',
      alt: 'Ilustração representando estratégias de email marketing',
      width: 210,
      height: 192,
    },
  },
  {
    id: 'content-creation',
    title: 'Content',
    subtitle: 'Creation',
    background: 'green',
    headingVariant: 'white',
    href: '#services',
    backgroundArrowLink: 'dark',
    image: {
      src: '/illustrations/services/content-creation.webp',
      alt: 'Ilustração representando criação de conteúdo digital',
      width: 210,
      height: 195,
    },
  },
  {
    id: 'analytics-tracking',
    title: 'Analytics and',
    subtitle: 'Tracking',
    background: 'dark',
    headingVariant: 'green',
    href: '#services',
    backgroundArrowLink: 'alternative-light',
    image: {
      src: '/illustrations/services/analytics.webp',
      alt: 'Ilustração representando análise de dados e monitoramento de métricas',
      width: 210,
      height: 170,
    },
  },
];
